language: python
python:
  - "3.5"
services:
  - postgresql
install:
  - pip install -r ./config/requirements.txt
before_script:
  - . ./config/test.env
  - psql -c "create database ${POSTGRES_DB};" -U $POSTGRES_USER
  - for f in ./src/tests/fixtures/metrics_db/sql/* ; do psql -d $POSTGRES_DB -f $f ; done
script:
  - flake8 ./src/*
  - nosetests ./src
