language: python
python:
  - "3.5"
services:
  - postgresql
env:
  - ALLOW_ORIGIN=*
  - API_DEBUG=False
  - SECRET_KEY=
  - POSTGRES_HOST=localhost
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=
  - POSTGRES_DB=metrics
install:
  - pip install -r ./config/requirements.txt
before_script:
  - psql -c 'create database metrics;' -U postgres
  - for f in ./src/tests/fixtures/metrics_db/sql/* ; do psql -f $f ; done
script:
  - flake8 ./src/*
  - nosetests ./src
