INSERT INTO country (country_id, country_code, country_name, continent_code) VALUES
('urn:iso:std:3166:-2:AF','AF','Afghanistan','AS'),
('urn:iso:std:3166:-2:AX','AX','Aland Islands','EU'),
('urn:iso:std:3166:-2:AL','AL','Albania','EU'),
('urn:iso:std:3166:-2:DZ','DZ','Algeria','AF'),
('urn:iso:std:3166:-2:AS','AS','American Samoa','OC'),
('urn:iso:std:3166:-2:AD','AD','Andorra','EU'),
('urn:iso:std:3166:-2:AO','AO','Angola','AF'),
('urn:iso:std:3166:-2:AI','AI','Anguilla','NA'),
('urn:iso:std:3166:-2:AQ','AQ','Antarctica','AN'),
('urn:iso:std:3166:-2:AG','AG','Antigua and Barbuda','NA'),
('urn:iso:std:3166:-2:AR','AR','Argentina','SA'),
('urn:iso:std:3166:-2:AM','AM','Armenia','AS'),
('urn:iso:std:3166:-2:AW','AW','Aruba','NA'),
('urn:iso:std:3166:-2:AU','AU','Australia','OC'),
('urn:iso:std:3166:-2:AT','AT','Austria','EU'),
('urn:iso:std:3166:-2:AZ','AZ','Azerbaijan','AS'),
('urn:iso:std:3166:-2:BS','BS','Bahamas','NA'),
('urn:iso:std:3166:-2:BH','BH','Bahrain','AS'),
('urn:iso:std:3166:-2:BD','BD','Bangladesh','AS'),
('urn:iso:std:3166:-2:BB','BB','Barbados','NA'),
('urn:iso:std:3166:-2:BY','BY','Belarus','EU'),
('urn:iso:std:3166:-2:BE','BE','Belgium','EU'),
('urn:iso:std:3166:-2:BZ','BZ','Belize','NA'),
('urn:iso:std:3166:-2:BJ','BJ','Benin','AF'),
('urn:iso:std:3166:-2:BM','BM','Bermuda','NA'),
('urn:iso:std:3166:-2:BT','BT','Bhutan','AS'),
('urn:iso:std:3166:-2:BO','BO','Bolivia','SA'),
('urn:iso:std:3166:-2:BQ','BQ','Bonaire, Sint Eustatius and Saba','NA'),
('urn:iso:std:3166:-2:BA','BA','Bosnia and Herzegovina','EU'),
('urn:iso:std:3166:-2:BW','BW','Botswana','AF'),
('urn:iso:std:3166:-2:BV','BV','Bouvet Island','AN'),
('urn:iso:std:3166:-2:BR','BR','Brazil','SA'),
('urn:iso:std:3166:-2:IO','IO','British Indian Ocean Territory','AS'),
('urn:iso:std:3166:-2:BN','BN','Brunei','AS'),
('urn:iso:std:3166:-2:BG','BG','Bulgaria','EU'),
('urn:iso:std:3166:-2:BF','BF','Burkina Faso','AF'),
('urn:iso:std:3166:-2:BI','BI','Burundi','AF'),
('urn:iso:std:3166:-2:KH','KH','Cambodia','AS'),
('urn:iso:std:3166:-2:CM','CM','Cameroon','AF'),
('urn:iso:std:3166:-2:CA','CA','Canada','NA'),
('urn:iso:std:3166:-2:CV','CV','Cape Verde','AF'),
('urn:iso:std:3166:-2:KY','KY','Cayman Islands','NA'),
('urn:iso:std:3166:-2:CF','CF','Central African Republic','AF'),
('urn:iso:std:3166:-2:TD','TD','Chad','AF'),
('urn:iso:std:3166:-2:CL','CL','Chile','SA'),
('urn:iso:std:3166:-2:CN','CN','China','AS'),
('urn:iso:std:3166:-2:CX','CX','Christmas Island','AS'),
('urn:iso:std:3166:-2:CC','CC','Cocos Keeling Islands','AS'),
('urn:iso:std:3166:-2:CO','CO','Colombia','SA'),
('urn:iso:std:3166:-2:KM','KM','Comoros','AF'),
('urn:iso:std:3166:-2:CG','CG','Congo','AF'),
('urn:iso:std:3166:-2:CK','CK','Cook Islands','OC'),
('urn:iso:std:3166:-2:CR','CR','Costa Rica','NA'),
('urn:iso:std:3166:-2:CI','CI','Cote d''ivoire Ivory Coast','AF'),
('urn:iso:std:3166:-2:HR','HR','Croatia','EU'),
('urn:iso:std:3166:-2:CU','CU','Cuba','NA'),
('urn:iso:std:3166:-2:CW','CW','Curacao','NA'),
('urn:iso:std:3166:-2:CY','CY','Cyprus','AS'),
('urn:iso:std:3166:-2:CZ','CZ','Czech Republic','EU'),
('urn:iso:std:3166:-2:CD','CD','Democratic Republic of the Congo','AF'),
('urn:iso:std:3166:-2:DK','DK','Denmark','EU'),
('urn:iso:std:3166:-2:DJ','DJ','Djibouti','AF'),
('urn:iso:std:3166:-2:DM','DM','Dominica','NA'),
('urn:iso:std:3166:-2:DO','DO','Dominican Republic','NA'),
('urn:iso:std:3166:-2:EC','EC','Ecuador','SA'),
('urn:iso:std:3166:-2:EG','EG','Egypt','AF'),
('urn:iso:std:3166:-2:SV','SV','El Salvador','NA'),
('urn:iso:std:3166:-2:GQ','GQ','Equatorial Guinea','AF'),
('urn:iso:std:3166:-2:ER','ER','Eritrea','AF'),
('urn:iso:std:3166:-2:EE','EE','Estonia','EU'),
('urn:iso:std:3166:-2:ET','ET','Ethiopia','AF'),
('urn:iso:std:3166:-2:FK','FK','Falkland Islands Malvinas','SA'),
('urn:iso:std:3166:-2:FO','FO','Faroe Islands','EU'),
('urn:iso:std:3166:-2:FJ','FJ','Fiji','OC'),
('urn:iso:std:3166:-2:FI','FI','Finland','EU'),
('urn:iso:std:3166:-2:FR','FR','France','EU'),
('urn:iso:std:3166:-2:GF','GF','French Guiana','SA'),
('urn:iso:std:3166:-2:PF','PF','French Polynesia','OC'),
('urn:iso:std:3166:-2:TF','TF','French Southern Territories','AN'),
('urn:iso:std:3166:-2:GA','GA','Gabon','AF'),
('urn:iso:std:3166:-2:GM','GM','Gambia','AF'),
('urn:iso:std:3166:-2:GE','GE','Georgia','AS'),
('urn:iso:std:3166:-2:DE','DE','Germany','EU'),
('urn:iso:std:3166:-2:GH','GH','Ghana','AF'),
('urn:iso:std:3166:-2:GI','GI','Gibraltar','EU'),
('urn:iso:std:3166:-2:GR','GR','Greece','EU'),
('urn:iso:std:3166:-2:GL','GL','Greenland','NA'),
('urn:iso:std:3166:-2:GD','GD','Grenada','NA'),
('urn:iso:std:3166:-2:GP','GP','Guadaloupe','NA'),
('urn:iso:std:3166:-2:GU','GU','Guam','OC'),
('urn:iso:std:3166:-2:GT','GT','Guatemala','NA'),
('urn:iso:std:3166:-2:GG','GG','Guernsey','EU'),
('urn:iso:std:3166:-2:GN','GN','Guinea','AF'),
('urn:iso:std:3166:-2:GW','GW','Guinea-Bissau','AF'),
('urn:iso:std:3166:-2:GY','GY','Guyana','SA'),
('urn:iso:std:3166:-2:HT','HT','Haiti','NA'),
('urn:iso:std:3166:-2:HM','HM','Heard Island and McDonald Islands','AN'),
('urn:iso:std:3166:-2:HN','HN','Honduras','NA'),
('urn:iso:std:3166:-2:HK','HK','Hong Kong','AS'),
('urn:iso:std:3166:-2:HU','HU','Hungary','EU'),
('urn:iso:std:3166:-2:IS','IS','Iceland','EU'),
('urn:iso:std:3166:-2:IN','IN','India','AS'),
('urn:iso:std:3166:-2:ID','ID','Indonesia','AS'),
('urn:iso:std:3166:-2:IR','IR','Iran','AS'),
('urn:iso:std:3166:-2:IQ','IQ','Iraq','AS'),
('urn:iso:std:3166:-2:IE','IE','Ireland','EU'),
('urn:iso:std:3166:-2:IM','IM','Isle of Man','EU'),
('urn:iso:std:3166:-2:IL','IL','Israel','AS'),
('urn:iso:std:3166:-2:IT','IT','Italy','EU'),
('urn:iso:std:3166:-2:JM','JM','Jamaica','NA'),
('urn:iso:std:3166:-2:JP','JP','Japan','AS'),
('urn:iso:std:3166:-2:JE','JE','Jersey','EU'),
('urn:iso:std:3166:-2:JO','JO','Jordan','AS'),
('urn:iso:std:3166:-2:KZ','KZ','Kazakhstan','AS'),
('urn:iso:std:3166:-2:KE','KE','Kenya','AF'),
('urn:iso:std:3166:-2:KI','KI','Kiribati','OC'),
('urn:iso:std:3166:-2:XK','XK','Kosovo','EU'),
('urn:iso:std:3166:-2:KW','KW','Kuwait','AS'),
('urn:iso:std:3166:-2:KG','KG','Kyrgyzstan','AS'),
('urn:iso:std:3166:-2:LA','LA','Laos','AS'),
('urn:iso:std:3166:-2:LV','LV','Latvia','EU'),
('urn:iso:std:3166:-2:LB','LB','Lebanon','AS'),
('urn:iso:std:3166:-2:LS','LS','Lesotho','AF'),
('urn:iso:std:3166:-2:LR','LR','Liberia','AF'),
('urn:iso:std:3166:-2:LY','LY','Libya','AF'),
('urn:iso:std:3166:-2:LI','LI','Liechtenstein','EU'),
('urn:iso:std:3166:-2:LT','LT','Lithuania','EU'),
('urn:iso:std:3166:-2:LU','LU','Luxembourg','EU'),
('urn:iso:std:3166:-2:MO','MO','Macao','AS'),
('urn:iso:std:3166:-2:MK','MK','Macedonia','EU'),
('urn:iso:std:3166:-2:MG','MG','Madagascar','AF'),
('urn:iso:std:3166:-2:MW','MW','Malawi','AF'),
('urn:iso:std:3166:-2:MY','MY','Malaysia','AS'),
('urn:iso:std:3166:-2:MV','MV','Maldives','AS'),
('urn:iso:std:3166:-2:ML','ML','Mali','AF'),
('urn:iso:std:3166:-2:MT','MT','Malta','EU'),
('urn:iso:std:3166:-2:MH','MH','Marshall Islands','OC'),
('urn:iso:std:3166:-2:MQ','MQ','Martinique','NA'),
('urn:iso:std:3166:-2:MR','MR','Mauritania','AF'),
('urn:iso:std:3166:-2:MU','MU','Mauritius','AF'),
('urn:iso:std:3166:-2:YT','YT','Mayotte','AF'),
('urn:iso:std:3166:-2:MX','MX','Mexico','NA'),
('urn:iso:std:3166:-2:FM','FM','Micronesia','OC'),
('urn:iso:std:3166:-2:MD','MD','Moldava','EU'),
('urn:iso:std:3166:-2:MC','MC','Monaco','EU'),
('urn:iso:std:3166:-2:MN','MN','Mongolia','AS'),
('urn:iso:std:3166:-2:ME','ME','Montenegro','EU'),
('urn:iso:std:3166:-2:MS','MS','Montserrat','NA'),
('urn:iso:std:3166:-2:MA','MA','Morocco','AF'),
('urn:iso:std:3166:-2:MZ','MZ','Mozambique','AF'),
('urn:iso:std:3166:-2:MM','MM','Myanmar Burma','AS'),
('urn:iso:std:3166:-2:NA','NA','Namibia','AF'),
('urn:iso:std:3166:-2:NR','NR','Nauru','OC'),
('urn:iso:std:3166:-2:NP','NP','Nepal','AS'),
('urn:iso:std:3166:-2:NL','NL','Netherlands','EU'),
('urn:iso:std:3166:-2:NC','NC','New Caledonia','OC'),
('urn:iso:std:3166:-2:NZ','NZ','New Zealand','OC'),
('urn:iso:std:3166:-2:NI','NI','Nicaragua','NA'),
('urn:iso:std:3166:-2:NE','NE','Niger','AF'),
('urn:iso:std:3166:-2:NG','NG','Nigeria','AF'),
('urn:iso:std:3166:-2:NU','NU','Niue','OC'),
('urn:iso:std:3166:-2:NF','NF','Norfolk Island','OC'),
('urn:iso:std:3166:-2:KP','KP','North Korea','AS'),
('urn:iso:std:3166:-2:MP','MP','Northern Mariana Islands','OC'),
('urn:iso:std:3166:-2:NO','NO','Norway','EU'),
('urn:iso:std:3166:-2:OM','OM','Oman','AS'),
('urn:iso:std:3166:-2:PK','PK','Pakistan','AS'),
('urn:iso:std:3166:-2:PW','PW','Palau','OC'),
('urn:iso:std:3166:-2:PS','PS','Palestine','AS'),
('urn:iso:std:3166:-2:PA','PA','Panama','NA'),
('urn:iso:std:3166:-2:PG','PG','Papua New Guinea','OC'),
('urn:iso:std:3166:-2:PY','PY','Paraguay','SA'),
('urn:iso:std:3166:-2:PE','PE','Peru','SA'),
('urn:iso:std:3166:-2:PH','PH','Phillipines','AS'),
('urn:iso:std:3166:-2:PN','PN','Pitcairn','OC'),
('urn:iso:std:3166:-2:PL','PL','Poland','EU'),
('urn:iso:std:3166:-2:PT','PT','Portugal','EU'),
('urn:iso:std:3166:-2:PR','PR','Puerto Rico','NA'),
('urn:iso:std:3166:-2:QA','QA','Qatar','AS'),
('urn:iso:std:3166:-2:RE','RE','Reunion','AF'),
('urn:iso:std:3166:-2:RO','RO','Romania','EU'),
('urn:iso:std:3166:-2:RU','RU','Russia','EU'),
('urn:iso:std:3166:-2:RW','RW','Rwanda','AF'),
('urn:iso:std:3166:-2:BL','BL','Saint Barthelemy','NA'),
('urn:iso:std:3166:-2:SH','SH','Saint Helena','AF'),
('urn:iso:std:3166:-2:KN','KN','Saint Kitts and Nevis','NA'),
('urn:iso:std:3166:-2:LC','LC','Saint Lucia','NA'),
('urn:iso:std:3166:-2:MF','MF','Saint Martin','NA'),
('urn:iso:std:3166:-2:PM','PM','Saint Pierre and Miquelon','NA'),
('urn:iso:std:3166:-2:VC','VC','Saint Vincent and the Grenadines','NA'),
('urn:iso:std:3166:-2:WS','WS','Samoa','OC'),
('urn:iso:std:3166:-2:SM','SM','San Marino','EU'),
('urn:iso:std:3166:-2:ST','ST','Sao Tome and Principe','AF'),
('urn:iso:std:3166:-2:SA','SA','Saudi Arabia','AS'),
('urn:iso:std:3166:-2:SN','SN','Senegal','AF'),
('urn:iso:std:3166:-2:RS','RS','Serbia','EU'),
('urn:iso:std:3166:-2:SC','SC','Seychelles','AF'),
('urn:iso:std:3166:-2:SL','SL','Sierra Leone','AF'),
('urn:iso:std:3166:-2:SG','SG','Singapore','AS'),
('urn:iso:std:3166:-2:SX','SX','Sint Maarten','NA'),
('urn:iso:std:3166:-2:SK','SK','Slovakia','EU'),
('urn:iso:std:3166:-2:SI','SI','Slovenia','EU'),
('urn:iso:std:3166:-2:SB','SB','Solomon Islands','OC'),
('urn:iso:std:3166:-2:SO','SO','Somalia','AF'),
('urn:iso:std:3166:-2:ZA','ZA','South Africa','AF'),
('urn:iso:std:3166:-2:GS','GS','South Georgia and the South Sandwich Islands','AN'),
('urn:iso:std:3166:-2:KR','KR','South Korea','AS'),
('urn:iso:std:3166:-2:SS','SS','South Sudan','AF'),
('urn:iso:std:3166:-2:ES','ES','Spain','EU'),
('urn:iso:std:3166:-2:LK','LK','Sri Lanka','AS'),
('urn:iso:std:3166:-2:SD','SD','Sudan','AF'),
('urn:iso:std:3166:-2:SR','SR','Suriname','SA'),
('urn:iso:std:3166:-2:SJ','SJ','Svalbard and Jan Mayen','EU'),
('urn:iso:std:3166:-2:SZ','SZ','Swaziland','AF'),
('urn:iso:std:3166:-2:SE','SE','Sweden','EU'),
('urn:iso:std:3166:-2:CH','CH','Switzerland','EU'),
('urn:iso:std:3166:-2:SY','SY','Syria','AS'),
('urn:iso:std:3166:-2:TW','TW','Taiwan','AS'),
('urn:iso:std:3166:-2:TJ','TJ','Tajikistan','AS'),
('urn:iso:std:3166:-2:TZ','TZ','Tanzania','AF'),
('urn:iso:std:3166:-2:TH','TH','Thailand','AS'),
('urn:iso:std:3166:-2:TL','TL','Timor-Leste East Timor','AS'),
('urn:iso:std:3166:-2:TG','TG','Togo','AF'),
('urn:iso:std:3166:-2:TK','TK','Tokelau','OC'),
('urn:iso:std:3166:-2:TO','TO','Tonga','OC'),
('urn:iso:std:3166:-2:TT','TT','Trinidad and Tobago','NA'),
('urn:iso:std:3166:-2:TN','TN','Tunisia','AF'),
('urn:iso:std:3166:-2:TR','TR','Turkey','EU'),
('urn:iso:std:3166:-2:TM','TM','Turkmenistan','AS'),
('urn:iso:std:3166:-2:TC','TC','Turks and Caicos Islands','NA'),
('urn:iso:std:3166:-2:TV','TV','Tuvalu','OC'),
('urn:iso:std:3166:-2:UG','UG','Uganda','AF'),
('urn:iso:std:3166:-2:UA','UA','Ukraine','EU'),
('urn:iso:std:3166:-2:AE','AE','United Arab Emirates','AS'),
('urn:iso:std:3166:-2:GB','GB','United Kingdom','EU'),
('urn:iso:std:3166:-2:US','US','United States of America','NA'),
('urn:iso:std:3166:-2:UM','UM','United States Minor Outlying Islands','OC'),
('urn:iso:std:3166:-2:UY','UY','Uruguay','SA'),
('urn:iso:std:3166:-2:UZ','UZ','Uzbekistan','AS'),
('urn:iso:std:3166:-2:VU','VU','Vanuatu','OC'),
('urn:iso:std:3166:-2:VA','VA','Vatican City','EU'),
('urn:iso:std:3166:-2:VE','VE','Venezuela','SA'),
('urn:iso:std:3166:-2:VN','VN','Vietnam','AS'),
('urn:iso:std:3166:-2:VG','VG','Virgin Islands, British','NA'),
('urn:iso:std:3166:-2:VI','VI','Virgin Islands, US','NA'),
('urn:iso:std:3166:-2:WF','WF','Wallis and Futuna','OC'),
('urn:iso:std:3166:-2:EH','EH','Western Sahara','AF'),
('urn:iso:std:3166:-2:YE','YE','Yemen','AS'),
('urn:iso:std:3166:-2:ZM','ZM','Zambia','AF'),
('urn:iso:std:3166:-2:ZW','ZW','Zimbabwe','AF');
